### ISSUE TITLE
Novo mantenedor

### ISSUE THREAD

**Issue by VitorSSSouzaBRESOFC** [The-Pixel-Project/official_devices#17]
### Device you want to apply for

Moto Edge 30 (dubai)

### Device Tree Sources

https://github.com/LineageOS/android_device_motorola_dubai
https://github.com/LineageOS/android_device_motorola_sm7325-common
https://github.com/TheMuppets/proprietary_vendor_motorola_dubai
https://github.com/TheMuppets/proprietary_vendor_motorola_sm7325-common
https://github.com/LineageOS/android_hardware_motorola.git
https://github.com/LineageOS/android_system_qcom
https://github.com/LineageOS/android_kernel_motorola_sm7325

### Number of ROM's you maintain officially/unofficially

01

### Any Exceptions/special concern?

No

### Telegram username

 @VTRSSSOUZABRES

### GitHub username

VitorSSSouzaBRESOFC

**Comment by hipexscape** [comment]
Hello @VitorSSSouzaBRESOFC 

Upon checking your device resources included in the application, I'm sorry that you don't satisfy the regulations for being accepted as an official maintainer. Hence, I'm closing the issue.

What went wrong:

The device tree is not yours and if you apply like this then it will be considered as KANG
What to fix:

Learn git properly
Gain some more experience in rom building field
Release an unofficial build
Go through the maintainer's requirements AGAIN.
Regards,
@hipexscape 
On behalf of The Pixel Project
