### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by itsprofessorX** [The-Pixel-Project/official_devices#22]
### Device you want to apply for

Realme 5/5i/5s (r5x)*

### Device Tree Sources

device tree > https://github.com/itsprofessorX/android_device_realme_r5x.git*

vendor tree > https://github.com/itsprofessorX/vendor_realme_r5x.git*

kernel tree > https://github.com/itsprofessorX/kernel_realme_r5x.git*

### Number of ROM's you maintain officially/unofficially

0*

### Any Exceptions/special concern?

NOTHING*

### Telegram username

https://t.me/Taylor_Oooo*

### GitHub username

itsprofessorX*

**Comment by JoeChirico** [comment]
Hello @itsprofessorX,

While reviewing the device tree resources linked in your application, I noticed that there aren’t any commits from you, not even a bringup commit. Therefore, the application got rejected

What to fix:
-  Make some commits 
-  Submit a proper bringup
-  Go through our documentation, especially regarding [maintainers requirements](https://github.com/The-Pixel-Project/official_devices/blob/fourteen-qpr3/docs/maintainers_requirements.md) and our [code of conduct](https://github.com/The-Pixel-Project/official_devices/blob/fourteen-qpr3/docs/maintainers_code_of_conduct.md).

Best regards,
@JoeChirico 
on behalf of The Pixel Project Team
