### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ashoss** [The-Pixel-Project/official_devices#28]
### Device you want to apply for

Pixel 5 (redfin) & Pixel 4a 5G (bramble)

### Device Tree Sources

• github.com/ashoss/android_device_google_bramble
• github.com/ashoss/android_device_google_redfin
• github.com/ashoss/android_device_google_redbull
• github.com/ashoss/android_kernel_google_redbull

Branch: aosp ( WIP, but stable )

### Number of ROM's you maintain officially/unofficially

one - Rising OS Unofficial

### Any Exceptions/special concern?

The device trees need some tidying up, but the build for redfin is stable with bramble coming soon. These devices share a common tree, but I have both devices. The vendor needed a lot of changes, mostly duplicates, and I will push those this week.

### Telegram username

@AndroidAsh

### GitHub username

ashoss

**Comment by amritokun** [comment]
Hello @ashoss 

Upon checking your device resources included in the application, I'm sorry that you don't satisfy the regulations for being accepted as an official maintainer. Hence, I'm closing the issue.

What went wrong:

**Not Enough Contribution Over Device Sources**
**Not Enough git Knowledge**

What to fix:
- Make some commits on your device sources
- Learn git properly & make yourself more skilled on git
- Go through our documentation, especially regarding [maintainers requirements](https://github.com/The-Pixel-Project/official_devices/blob/fourteen-qpr3/docs/maintainers_requirements.md) and our [code of conduct](https://github.com/The-Pixel-Project/official_devices/blob/fourteen-qpr3/docs/maintainers_code_of_conduct.md).


Regards,
@Takixamru 
On behalf of The Pixel Project team.
