### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Karan-Frost** [The-Pixel-Project/official_devices#30]
### Device you want to apply for

Redmi Note 9S/Redmi Note 9 Pro/Redmi Note 10 Lite/Redmi Note 9 Pro Max/Poco M2 Pro (miatoll)

### Device Tree Sources

# Device Tree
https://github.com/ihsanulrahman/device_xiaomi_miatoll/tree/14-tpp

# Vendor Tree
https://github.com/ihsanulrahman/vendor_xiaomi_miatoll/tree/udc

# Kernel Tree
https://github.com/c0smic-Lab/kernel_xiaomi_sm6250/tree/main

### Number of ROM's you maintain officially/unofficially

1

### Any Exceptions/special concern?

# Co-maintaining
We are two people @Karan-Frost and @ihsanulrahman who would like to maintain this rom in partnership.

### Telegram username

https://t.me/Under_Frost and https://t.me/ihsanulrahman

### GitHub username

@Karan-Frost and @ihsanulrahman

**Comment by amritokun** [comment]
Hey @Karan-Frost 

As Per Conversation Over Telegram, I am 
Approving Your Application. 
Have A Great Day Ahead. 

Regards,
@Takixamru 
On behalf of The Pixel Project team
