### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by yassshhhh15** [The-Pixel-Project/official_devices#35]
### Device you want to apply for

realme GT NEO 3T (spartan)

### Device Tree Sources

https://github.com/yassshhhh15/android_device_realme_spartan
https://github.com/yassshhhh15/proprietary_vendor_realme_spartan
https://github.com/yassshhhh15/android_hardware_oplus
https://github.com/yassshhhh15/android_kernel_realme_sm8250

### Number of ROM's you maintain officially/unofficially

2

### Any Exceptions/special concern?

Have been maintaining this rom since 2 months 

### Telegram username

@yassshhhh_15

### GitHub username

@yassshhhh15

**Comment by hipexscape** [comment]
Hey yassshhhh15,

While going through your trees, we found some issues with it. Let me describe few of them 

1. Please manage proper authorship. Refer [maintainer ship requirements](https://github.com/The-Pixel-Project/official_devices/blob/fourteen-qpr3/docs/maintainers_requirements.md)
 https://github.com/yassshhhh15/android_device_realme_spartan/commit/2a7080b683435b78f41c5c0897b252745555bd55
     https://github.com/yassshhhh15/android_device_realme_spartan/commit/aba9f406abaa3eb2591f0ea19a57ab5e0bdfcf21
     https://github.com/yassshhhh15/android_device_realme_spartan/commit/a4639b9614706889f03013965ed2d4d0c9241bdf
    https://github.com/yassshhhh15/android_device_realme_spartan/commit/c8b99f19041a0b9e46af724b0be383e55205b636


2. So many reverts in kernel, why ? May I know the reason ?

Regards,
@hipexscape,
On behalf of **The Pixel Project Team**.

**Comment by yassshhhh15** [comment]
Sir, as mentioned above I've managed to give proper authorship to the commits now.
https://github.com/yassshhhh15/android_device_realme_spartan
Also those commit reverts in kernel tree were a result of a beginner trying to mess with kernel tree lol, hopefully I've managed to cleanup that too (shifted to other kernel tree)
https://github.com/yassshhhh15/android_kernel_realme_sm8250

**Comment by amritokun** [comment]
Hello @yassshhhh15 

Upon checking your device resources included in the application, I'm sorry that you don't satisfy the regulations for being accepted as an official maintainer. Hence, I'm closing the issue.

What went wrong:

- Not Enough git Knowledge

What to fix:

- Learn git properly & make yourself more skilled on git
- Go through our documentation, especially regarding [maintainers requirements](https://github.com/The-Pixel-Project/official_devices/blob/fourteen-qpr3/docs/maintainers_requirements.md) and our [code of conduct](https://github.com/The-Pixel-Project/official_devices/blob/fourteen-qpr3/docs/maintainers_code_of_conduct.md).

Regards,
@Takixamru
On behalf of The Pixel Project team.
