### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by swiitchOFF** [The-Pixel-Project/official_devices#39]
### Device you want to apply for

Xiaomi 11T pro (vili)

### Device Tree Sources

1) https://github.com/swiitch-OFF-Lab/device_xiaomi_vili/tree/aosp
2) https://github.com/swiitch-OFF-Lab/android_device_xiaomi_sm8350-common/tree/aosp-14
3) https://github.com/swiitch-OFF-Lab/vendor_xiaomi_vili/tree/14.0
4) https://github.com/Spanish-or-Vanish/vendor_xiaomi_sm8350-common/tree/A14-rebase
5) https://github.com/swiitch-OFF-Lab/kernel_xiaomi_sm8350/tree/udc
6) https://github.com/swiitch-OFF-Lab/hardware_dolby

### Number of ROM's you maintain officially/unofficially

officially crDroid and unofficially aospa

### Any Exceptions/special concern?

before applying for official already made 2 unofficial TPP builds
Old tree before rebase https://github.com/swiitch-OFF-Lab/android_device_xiaomi_sm8350-common/tree/aosp

### Telegram username

@MIUI_users_r_GAY

### GitHub username

https://github.com/swiitchOFF

**Comment by swiitchOFF** [comment]
Sorry could u reject my application ig i wouldn't be able to maintain official this time due to my busy schedule

**Comment by hipexscape** [comment]
> Sorry could u reject my application ig i wouldn't be able to maintain official this time due to my busy schedule

As you wish .....
