### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Angelpro09xd** [The-Pixel-Project/official_devices#40]
### Device you want to apply for

Redmi Note 13 4G (sapphire)

### Device Tree Sources

https://github.com/sm6225-unified/device_qcom_sepolicy_vndr.git device/qcom/sepolicy_vndr/sm6225
https://github.com/sm6225-unified/hardware_qcom-caf_common.git hardware/qcom-caf/common
https://github.com/sm6225-unified/vendor_qcom_opensource_agm.git hardware/qcom-caf/sm6225/audio/agm
https://github.com/sm6225-unified/vendor_qcom_opensource_arpal-lx.git hardware/qcom-caf/sm6225/audio/pal
https://github.com/sm6225-unified/hardware_qcom_audio-ar.git hardware/qcom-caf/sm6225/audio/primary-hal
https://github.com/sm6225-unified/vendor_qcom_opensource_data-ipa-cfg-mgr.git hardware/qcom-caf/sm6225/data-ipa-cfg-mgr
https://github.com/sm6225-unified/vendor_qcom_opensource_dataipa.git hardware/qcom-caf/sm6225/dataipa
https://github.com/sm6225-unified/hardware_qcom_display.git hardware/qcom-caf/sm6225/display
https://github.com/sm6225-unified/hardware_qcom_media.git hardware/qcom-caf/sm6225/media
https://github.com/sm6225-unified/device_xiaomi_sepolicy.git device/xiaomi/sepolicy
https://github.com/sm6225-unified/hardware_xiaomi.git hardware/xiaomi https://github.com/ReStranger/device_xiaomi_miuicamera-sapphire.git device/xiaomi/miuicamera-sapphire
https://github.com/ReStranger/vendor_xiaomi_miuicamera-sapphire.git vendor/xiaomi/miuicamera-sapphire https://github.com/crdroidandroid/android_device_xiaomi_sapphire.git device/xiaomi/sapphire
https://github.com/crdroidandroid/proprietary_vendor_xiaomi_sapphire.git vendor/xiaomi/sapphire
https://github.com/crdroidandroid/android_kernel_xiaomi_sapphire.git  device/xiaomi/sapphire-kernel

### Number of ROM's you maintain officially/unofficially

2

### Any Exceptions/special concern?

I am a new dev, I really like this, and I want to continue learning more every day, I have made a build of this rom for this device (sapphire), and the reviews from the testers are very positive

### Telegram username

@Angelpro09_Dev

### GitHub username

Angelpro09xd

**Comment by hipexscape** [comment]
Hello @Angelpro09xd,

Upon checking your device resources included in the application, I'm sorry that you don't satisfy the regulations for being accepted as an official maintainer. Hence, I'm closing the issue.

What went wrong:

- Not Enough git Knowledge
- Less contribution on your trees (you are using the trees of other devs)

What to fix:
- Learn git properly & make yourself more skilled on git

Regards,
@hipexscape
On behalf of The Pixel Project team.
