### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kenway214** [The-Pixel-Project/official_devices#8]
### Device you want to apply for

Poco F5 (marble)

### Device Tree Sources

https://github.com/poco-f5-mable

### Number of ROM's you maintain officially/unofficially

1

### Any Exceptions/special concern?

nothing..

### Telegram username

https://t.me/ph12nex

### GitHub username

kenway214

**Comment by sajidshahriar72543** [comment]
Hello @kenway214 

Thanks for the application. Could you please send the link of the resources (dt, vt and kt & common trees if applicable) separately specifying the exact branch you are applying with? It'll will ease out the process greatly.

Regards 
@sajidshahriar72543 
On behalf of The Pixel Project team.

**Comment by hipexscape** [comment]
Hey @kenway214,

I just had a look at your trees and found that :

- I don't think you need these flags on a gapps only rom ?
https://github.com/poco-f5-mable/device_xiaomi_marble/commit/edfbe8f5a739e49d873f880ff822daeecdfacfe4#diff-a97990e78aebb03c56af3be3025a5fa678501b570a507c57a55166e303535574R23-R25

Regards,
@hipexscape 
On behalf of The Pixel Project team.

**Comment by kenway214** [comment]
BUILD_WITH_GAPPS := true 
this needed 
https://github.com/poco-f5-mable/device_xiaomi_sm8450-common/blob/aosp-14/BoardConfigCommon.mk#L197

other one dont needed forgot to remove when doing bringup

**Comment by MODEDGES24** [comment]
Hey, just to clarify you do not need the gapps flags, as google apps are built by deafult thanks

**Comment by hipexscape** [comment]
> BUILD_WITH_GAPPS := true this needed https://github.com/poco-f5-mable/device_xiaomi_sm8450-common/blob/aosp-14/BoardConfigCommon.mk#L197
> 
> other one dont needed forgot to remove when doing bringup

Hey,

You can really remove ifneq wrapper from `BOARD_PRODUCTIMAGE_EXTFS_INODE_COUNT`  flag since this is a gapps only rom.

Regards,
@hipexscape
On behalf of The Pixel Project team.

**Comment by kenway214** [comment]
https://github.com/poco-f5-mable/device_xiaomi_marble -b Pixel-14
https://github.com/poco-f5-mable/device_xiaomi_sm8450-common.git -b pixel-14

UPDATED

**Comment by hipexscape** [comment]
Hey @kenway214,

- Please drop this commit as we don't allow modifying security patch
https://github.com/poco-f5-mable/device_xiaomi_sm8450-common/commit/78d8f88a66329083f1f87bd053357efd72356a21
https://github.com/poco-f5-mable/device_xiaomi_sm8450-common/commit/03694cc1259a2282295fd4597d829491f04a693c

Regards,
@hipexscape
On behalf of The Pixel Project team.

**Comment by kenway214** [comment]
1. security patch commit dropped
2. ab device when update rom twrp replaced by source recovery and people alawys cry as they forgot to flash twrp after flashing rom.. well I added source recovery
3. I think bcr is good those who dont want root bcr non root alternative way to get call recording .. if needed can drop that

**Comment by hipexscape** [comment]
> 1. security patch commit dropped
> 2. ab device when update rom twrp replaced by source recovery and people alawys cry as they usually forget to flash twrp after flashing rom.. well I added source recovery
> 3. I think bcr is good those who dont want root bcr non root alternative way to get call recording .. if needed can drop that

Hey @kenway214,

- Don't worry about BCR, we will ship it as prebuild in a future update of tpp
- Please drop MIUI stuffs then we are ready to go 

Regards,
@hipexscape
On behalf of The Pixel Project team.

**Comment by kenway214** [comment]
all done 

https://github.com/poco-f5-mable/device_xiaomi_marble  -b Pixel-14

**Comment by hipexscape** [comment]
Hey @kenway214,

Please drop this commit 
https://github.com/poco-f5-mable/vendor_xiaomi_miuicamera-marble/commit/f57ea9b67aab1e4dc9618e77479b4d692e000dc5

Regards,
@hipexscape
On behalf of The Pixel Project team.

**Comment by kenway214** [comment]
check branch -b pixel-14 already dropped

**Comment by hipexscape** [comment]
Hey @kenway214 ,

Please message me on telegram
https://t.me/hipexscape

Regards,
@hipexscape
On behalf of The Pixel Project team.
